Update README.rst
kdious/libinsult-client-python pull request #2
Opened 2019-10-17 08:47 UTC by Kumsy

@kdious updated README.rst (explanation rewording).

2019-10-17 17:30 UTC, kdious commented on README.rst
> +to test against potential API changes, unit tests call PurgoMalum's
Change this to: 

```
Tests have been for python 2.7 and python 3 using ``pytest``. The unit
tests do call the actual LibInsult's `production API <https://insult.mattbas.org/api/>`__ in order to test
against potential API changes.
```

2019-10-17 17:30 UTC, kdious commented on README.rst
> +to test against potential API changes, unit tests call PurgoMalum's
This should then render "production API" as a hyperlink to the API page.

2019-10-17 17:31 UTC, kdious requested changes
See comment.

2019-10-17 21:06 UTC, Kumsy commented
@kdious documentation with hyperlink to production API added.

2019-10-19 17:27 UTC, kdious approved these changes

2019-10-19 17:27 UTC, merged